### ISSUE TITLE
Extension does not work

### ISSUE THREAD

**Issue by Knies-IT** [teal-bauer/moneymoney-ext-trading212#4]
Hello, unfortunately the extension does not work for me, despite API key. Can you check that?

Log: 
10:58:29  Lade Kontenliste ...
          Web Banking Engine: Using user-supplied extension Trading212.lua version 0.32.
          Protocol version: Web Scraping
          Server address: https://trading212.com/
          Cleaning up local cache
          Getting account information
          Sending: GET https://live.trading212.com/api/v0/equity/account/info
10:58:30  HTTPS response: HTTP/1.1 401 Unauthorized
          Received: {"error":401,"error_description":"Unauthorized"}
          Trading212.lua: Trading212.lua:143: Login to server failed.

**Comment by teal-bauer** [comment]
I have no way to debug that and it works fine for me. Make sure your API key is for the live platform and not the testing environment, and make sure you added the correct API information in the right place. You can re-auth via context menu on the account in MoneyMoney

**Comment by basis7net** [comment]
Hello, I updated to the new version 0.32 of the lua (moneymoney 2.4.60) and now have the exact same error message as above - with the 0.31 Version I was able to login (even that the only information I could access was the portfolio value not the Pie. I installed the API Key as before. 

18:15:08  Lade Kontenliste ...
          Web Banking Engine: Using user-supplied extension Trading212.lua version 0.32.
          Protocol version: Web Scraping
          Server address: https://trading212.com/
          Cleaning up local cache
          Getting account information
          Sending: GET https://live.trading212.com/api/v0/equity/account/info
          HTTPS response: HTTP/1.1 401 Unauthorized
          Received: {"error":401,"error_description":"Unauthorized"}
          Trading212.lua: Trading212.lua:143: Login to server failed.

**Comment by mweidle73** [comment]
I have the same issue with version 0.32 and MoneyMoney version 2.4.66 from the App Store.

The problems seems to be that a newly created API Key from Trading 212 has two components - an ID and a Secret - but when I want to add an account using the script I only ever get asked to provide an API Key and neither the ID nor the Secret is sufficient for the authentication on the API.

I guess either the script must be adopted to ask for user/password combination or it should handle an API Key consisting of two parts for example with a ':' as a delimiter.

**Comment by teal-bauer** [comment]
Fixed in v0.40 (commit 53e7b04). Trading212 now uses HTTP Basic Auth with API Key + Secret. When adding the account in MoneyMoney, enter your **API Key** in the username field and **API Secret** in the password field.

**Comment by mweidle73** [comment]
Trading212.lua: Ignoring 'Trading212.lua' because signature verification failed.

Can you please sign the release?

**Comment by teal-bauer** [comment]
No, I cannot, that is something MRH have to do. Please be patient.

**Comment by teal-bauer** [comment]
You can enable developer mode in the meantime to skip the signature verification, as documented in the MoneyMoney docs iirc.

**Comment by mweidle73** [comment]
Ok, I disabled signature verification in the settings and now it shows me the extension v0.41 for Trading 212 but I still cannot use it with my version of MoneyMoney since I still only get a prompt for API-Key and nothing else.

Could you change the script in a a way that it looks for a ":" delimiter so I could input both values the id and the secret into just one input field please?

**Comment by teal-bauer** [comment]
I'll have to ask you to please wait until the next actual release is ready.

**Comment by mweidle73** [comment]
Just to let you know: v0.42 is now working for me if I use the workaround with the ":" delimiter in the API-Key input field.

Thank you!

**Comment by teal-bauer** [comment]
Yeah, I added a workaround for now, but I would still recommend that users keep signature checks on and hold off on non-release versions for security reasons. Glad to hear it works though :)
